name: .NET and Jest Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Setup .NET for NUnit tests
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    # Restore and Build .NET Project
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
      
    # Run NUnit Tests
    - name: Run NUnit Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Tests

    # Setup Node.js for Jest testing
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Use latest LTS version
        
    # Install dependencies for Jest tests
    - name: Install Node.js dependencies
      run: npm ci
      working-directory: ./src/wwwroot/js

    # Ensure Jest has execution permissions
    - name: Grant Jest Execution Permissions
      run: chmod +x node_modules/.bin/jest
      working-directory: ./src/wwwroot/js

    # Run Jest Tests
    - name: Run Jest Tests
      run: npx jest
      working-directory: ./src/wwwroot/js
