name: Trigger auto deployment for sm

# When this action will be executed
on:
  workflow_run:
    workflows: [" .NET and Jest Build and Test"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SM_REGISTRY_PASSWORD }}
          containerAppName: sm
          resourceGroup: fathy-calc_group
          imageToBuild: fathyattia/sm:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


