# Workflow name
name: .NET and Jest Build and Test

# Trigger on push and pull request to master branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  # First job: Build the application
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./src


  # Second job: Run all tests
  test:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Run NUnit Tests
        run: dotnet test --verbosity normal
        working-directory: ./tests

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./src/wwwroot/js

      - name: Grant Jest Execution Permissions
        run: chmod +x node_modules/.bin/jest
        working-directory: ./src/wwwroot/js

      - name: Run Jest Tests
        run: npx jest
        working-directory: ./src/wwwroot/js