# Workflow name
name: .NET and Jest Build and Test

# Trigger on push and pull request to master branch
on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:

  # ==========================================================
  # Job 1: Build the .NET application
  # ==========================================================
  build:
    name: Build .NET
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build application
        run: dotnet build --no-restore
        working-directory: ./src


  # ==========================================================
  # Job 2: Run NUnit tests
  # ==========================================================
  nunit-tests:
    name: NUnit Tests
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Run NUnit Tests
        run: dotnet test --verbosity normal
        working-directory: ./tests


  # ==========================================================
  # Job 3: Run Jest tests
  # ==========================================================
  jest-tests:
    name: Jest Tests
    needs: nunit-tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./src/wwwroot/js

      - name: Grant Jest Execution Permissions
        run: chmod +x node_modules/.bin/jest
        working-directory: ./src/wwwroot/js

      - name: Run Jest Tests
        run: npx jest
        working-directory: ./src/wwwroot/js